---
- name: Ensure Fluent Bit service is started and enabled (Linux)
  ansible.builtin.service:
    name: fluent-bit
    state: started
    enabled: true
  when: ansible_os_family == 'RedHat'
  tags:
    - fluentbit_service

- name: Ensure Fluent Bit service is started and enabled (Windows)
  ansible.builtin.service:
    name: fluent-bit
    state: started
    enabled: true
  when: ansible_os_family == 'Windows'
  tags:
    - fluentbit_service
