---
- name: Ensure Fluent Bit service is started and enabled (Linux)
  ansible.builtin.service:
    name: fluent-bit
    state: started
    enabled: true
  when: ansible_os_family == 'RedHat'
  tags:
    - fluentbit_service

- name: Ensure Fluent Bit service is started and enabled (Windows)
  ansible.windows.win_service:
    description: Fluent Bit Service
    display_name: FluentBit
    name: fluent-bit
    path: "{{ fluentbit_windows_install_dir }}\\bin\\fluent-bit.exe -c \"{{ fluentbit_windows_install_dir }}\\conf\\fluent-bit.conf\""
    state: started
    start_mode: auto
    username: "LocalService"
  when: ansible_os_family == 'Windows'
  tags:
    - fluentbit_service
